# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# Orchestrate or schedule a set of jobs
workflows:
  welcome:
    jobs:
      build:
        docker:
          - image: lash/xfoo
            environment:
              XFOO: barr
        steps:
          run: |
            docker run --name xfoo lash/xfoo
