version: 2.1
jobs:
  build:
    docker:
      - image: lash/xfoo
        environment:
          XFOO: "$XXFOO"
    steps:
      - run: /usr/bin/python /do.py
workflows:
  version: 2.1
  yeah:
    jobs:
      - build
